import jsPDF from "jspdf";

const generateReport = (analysis) => {
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    let y = 20;
    let page = 1;

    const addFooter = () => {
        doc.setDrawColor(200);
        doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);

        doc.setFontSize(10);
        doc.setTextColor(120);

        doc.text(
            "Generated by Narrative Nexus",
            20,
            pageHeight - 8
        );

        doc.text(
            `Page ${page}`,
            pageWidth - 30,
            pageHeight - 8
        );
    };

    const checkPage = (spaceNeeded = 15) => {
        if (y + spaceNeeded > pageHeight - 25) {
            addFooter();
            doc.addPage();
            page++;
            y = 20;
        }
    };

    // ===== Title =====

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(0, 102, 204);
    doc.text("Narrative Nexus", 20, y);

    y += 10;

    doc.setFontSize(14);
    doc.setTextColor(80);
    doc.text("AI Powered Document Intelligence", 20, y);

    y += 15;

    doc.setFontSize(11);
    doc.setTextColor(100);

    doc.text(
        `Generated on: ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 18;

    // ===== Statistics =====

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 204);
    doc.text("Document Statistics", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0);

    const stats = [
        ["Words", analysis.statistics.word_count],
        ["Characters", analysis.statistics.character_count],
        ["Sentences", analysis.statistics.sentence_count],
        ["Reading Time", `${analysis.statistics.reading_time} min`],
    ];

    stats.forEach(([label, value]) => {
        checkPage();
        doc.text(`${label}: ${value}`, 25, y);
        y += 8;
    });

    y += 8;

    // ===== Sentiment =====

    checkPage(20);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 204);
    doc.text("Sentiment Analysis", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0);

    doc.text(`Label: ${analysis.sentiment.label}`, 25, y);
    y += 8;

    doc.text(`Confidence: ${analysis.sentiment.score}%`, 25, y);

    y += 15;

    // ===== Topics =====

    checkPage(20);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 204);
    doc.text("AI Topic Discovery", 20, y);

    y += 10;

    analysis.topics.forEach((topic, index) => {
        checkPage(35);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(0);

        doc.text(`${index + 1}. ${topic.title}`, 20, y);

        y += 8;

        doc.setFont("helvetica", "normal");

        const keywordText = `Keywords: ${topic.keywords.join(", ")}`;
        const keywordLines = doc.splitTextToSize(keywordText, 165);

        doc.text(keywordLines, 25, y);

        y += keywordLines.length * 7;

        topic.representative_sentences.forEach((sentence) => {
            checkPage(20);

            const lines = doc.splitTextToSize(
                "• " + sentence,
                160
            );

            doc.text(lines, 30, y);

            y += lines.length * 7;
        });

        y += 8;
    });

    // ===== Summary =====

    checkPage(25);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 102, 204);
    doc.text("AI Generated Summary", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0);

    const summaryLines = doc.splitTextToSize(
        analysis.summary,
        170
    );

    summaryLines.forEach((line) => {
        checkPage();
        doc.text(line, 20, y);
        y += 7;
    });

    addFooter();

    doc.save("Narrative_Nexus_Report.pdf");
};

export default generateReport;